version: "3"

services:
  stock_prediction:
    image: stock_prediction
    build:
      context: ../
      dockerfile: ./devOps/dev.Dockerfile
    container_name: stock_prediction
    command:
      bash -c "uvicorn main:app --reload --host 0.0.0.0 --port 7070"
    ports:
      - "7070:7070"
    networks:
      - app-internal-net
    depends_on:
      - model_db

  model_db:
    image: postgres
    restart: always
    container_name: model_db
    env_file:
      - db.dev.env
#    volumes:
#      - model:/var/lib/postgresql/data
    networks:
      - app-internal-net

networks:
  app-internal-net:
    external: true
#
#volumes:
#  model: